### ISSUE TITLE
app size

### ISSUE THREAD

**Issue by annihat** [adywizard/car-locator#1]
Hi, 
 can I ask why the app is so big? 28.9 MB seems excessive (F-Droid version)

**Comment by adywizard** [comment]
I'm so sorry, however I can't do anything about it, The app is written with Kivy (python) with all this features app goes up to 30 MB, I know it's a lot for single app, but it's due to how Kivy packs everything on android. I can make it slimmer, however it would be very basic app, the previously one was around 16 MB without animations and Bluetooth pairing. I soon as I add more stuff app's size groves.

**Comment by adywizard** [comment]
> Hi,
> can I ask why the app is so big? 28.9 MB seems excessive (F-Droid version)

I think I accidentally included gifs folder in apk, will fix it later when I get home.

**Comment by adywizard** [comment]
> Hi,
> can I ask why the app is so big? 28.9 MB seems excessive (F-Droid version)

I'm closing this issue, new version can be found in bin folder, app size is around 18MB now.
